package com.sample
 
import com.sample.Order;
import com.sample.Client;
 
rule "Regular memership discount"
    when
    	$c: Client(type == Client.REGULAR)
        $o: Order(client == $c)
    then
    	System.out.println("Regular memership discount");
		$o.applyRegularDisccount();
end

rule "Premium memership discount"
    when
    	$c: Client(type == Client.PREMIUM)
        $o: Order(client == $c, products.size < 4)
    then
    	System.out.println("Premium memership discount");
		$o.applyPremiumDisccount();
end

rule "Premium memership discount and 4 products bought"
    when
    	$c: Client(type == Client.PREMIUM)
        $o: Order( client == $c, products.size >= 4)
    then
    	System.out.println("Premium memership discount and 4 products bought");
		$o.applyPremiumAdittionalDisccount();
		$o.sendEmailToCFO("a.bayona@uniandes.edu.co");
end


