package com.sample
 
import com.sample.Order;
import com.sample.Client;
 
rule "Action is of type LOAD_ANEXO_5_FILE and user does not have permissions"
    when
    	$c: Action(actionType == Role.LOAD_ANEXO_5_FILE)
        $u: User(!roleIds.contains(Role.USER_ROLE_ID))
    then
    	System.out.println("User does not have permissions to upload ANEXO 5. Request permissions to your administrator");
end

rule "Upload CSV file to the system if CSV and not empty"
    when
        $c: Action(actionType == Role.LOAD_ANEXO_5_FILE)
        $u: User(roleIds.contains(Role.USER_ROLE_ID))
        eval($c.validateCSVFileType()) // Check if the file is a CSV file
        eval($c.validateFileIsNotEmpty()) // Check if the file is not empty
    then
        System.out.println("Uploading CSV file to the system");
        // Perform the file upload operation
        $c.loadDataToPortal();
end

rule "Action is of type GENERATE_CUPOS_PORTAL and user does not have permissions"
    when
    	$c: Action(actionType == Role.GENERATE_CUPOS_PORTAL)
        $u: User(!roleIds.contains(Role.USER_ROLE_ID))
    then
    	System.out.println("User does not have permissions to create mass cupos. Request permissions to your administrator");
end


